Test
JoanBoters/ProyectoFinal pull request #7
Opened 2021-01-13 16:44 UTC by JoanBoters

Hemos añadido los test y la acción, pero no se si ha funcionado!!

2021-01-15 16:54 UTC, aalcacer requested changes
Está muy bien.

Como consejo en general, deberias poner más espacios al programar, por ejemplo detras de una coma siempre va un espacio. Estas reglas las puedes encontrar en cualquier guía de estilo de programación.

Son detalles que no afectan al rendimiento del código pero lo hacen mucho más visual :)

2021-01-15 16:54 UTC, aalcacer commented on tests/testthat/test-regla_simpson.R
> +  expect_equal(regla_simpson(-1,1,function(x){return(x^2)}),2/3)
Si quieres ver que las actions funcionan de verdad, pon un test mal, haz un commit y verás cómo falla. Luego, haz otro commit solucionando el test y me pones de revisor otra vez. Vale?

2021-01-15 17:15 UTC, aalcacer requested changes
¿Has hecho los commits que te he dicho?

2021-01-15 17:25 UTC, JoanBoters reviewed
> ¿Has hecho los commits que te he dicho?

No, porque tengo claro que si que lo hace el github. Cuando te envié el correo no lo tenia claro, porque no me salia el punto amarillo, pero al rato me salió. Per, si quieres los hago.

2021-01-15 17:25 UTC, JoanBoters commented on tests/testthat/test-regla_simpson.R
> +  expect_equal(regla_simpson(-1,1,function(x){return(x^2)}),2/3)
Lo he comprobado en el caso práctico he visto como se va descargando todo en el apartado de actions. Si quieres que canvie algo antes de entregarlo me lo dices. Gracias!!

2021-01-26 16:03 UTC, aalcacer approved these changes

2021-01-26 21:20 UTC, merged